server:
  port: 8808
jt808:
  server:
    port: 6808
  built-components:
    component-statistics:
      enabled: true
    request-handlers:
      enabled: true
  features:
    program-param-printer:
      enabled: true
      pretty: false
  msg-processor:
    executor-group:
      thread-count: 32
      pool-name: 808-msg-processor
      max-pending-tasks: 128
  request-sub-package-storage:
    type: caffeine
    caffeine:
      ttl: 30s
      maximum-size: 1024
  response-sub-package-storage:
    type: caffeine
    caffeine:
      maximum-size: 1024
      ttl: 3m

logging:
  level:
    root: info
    io.github.hylexus: info
    # 将默认解码器的日志级别调整到debug 来观察分包请求消息的解码
    jt-808.request.decoder: debug
    # 将请求分包暂存器(默认为基于Caffeine的实现)的日志级别调整的debug 来观察分包请求的处理过程
    io.github.hylexus.jt.jt808.support.codec.impl.CaffeineJt808RequestSubPackageStorage: debug
    jt-808.response.encoder: debug
    jt-808.command-sender: debug
