server:
  port: 8808
logging:
  level:
    root: info
    io.github.hylexus: info
    jt-808.request.decoder: debug
    jt-808.response.encoder: debug
jt808:
  built-components:
    component-statistics:
      enabled: true
    request-handlers:
      enabled: true
  protocol:
    max-frame-length: 1024
  server:
    port: 6808
    boss-thread-count: 0
    worker-thread-count: 0
    idle-state-handler:
      enabled: true
      reader-idle-time: 20m
      writer-idle-time: 20m
      all-idle-time: 20m
  msg-processor:
    executor-group:
      thread-count: 20
      max-pending-tasks: 512
  request-sub-package-storage:
    type: caffeine # caffeine || none
    ## 当且仅当 jt808.request-sub-package-storage.type = caffeine 时生效
    caffeine:
      # 最多缓存多少条消息
      maximum-size: 1024
      # 最大缓存时间
      ttl: 45s
  response-sub-package-storage:
    type: caffeine # caffeine || redis || none
    ## 当且仅当 jt808.response-sub-package-storage.type = caffeine 时生效
    caffeine:
      # 最多缓存多少条消息
      maximum-size: 1024
      # 最大缓存时间
      ttl: 45s
    ## 当且仅当 jt808.response-sub-package-storage.type = redis 时生效
    redis:
      # 最大缓存时间
      ttl: 1m

