server:
  port: 8808
logging:
  level: info
  level.io.github.hylexus: debug
jt808:
  print-component-statistics: true
  protocol:
    version: auto_detection
  entity-scan:
    enabled: true
    enable-builtin-entity: true
    register-builtin-request-msg-converters: true
    base-packages: io.github.hylexus.jt808.samples.mixedversion.entity.req
  converter-scan:
    enabled: true
    register-builtin-request-msg-converters: true
    base-packages: io.github.hylexus.jt808.samples.mixedversion.entity.converter
  handler-scan:
    enabled: true
    register-builtin-msg-handlers: true
    base-packages: io.github.hylexus.jt808.samples.mixedversion.handler
  server:
    port: 6808
    boss-thread-count: 0
    worker-thread-count: 0
  msg-processor:
    thread-pool:
      core-pool-size: 4
      maximum-pool-size: 4
      keep-alive-time: 60s
      blocking-queue-size: 20
      thread-name-format: '808-msg-processor-%d'


